version: "3.8"
services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FORCE_DYNAMIC_LIBEBM=true
    container_name: altrustworthyai_app

  tests:
    build: .
    command: ["python", "-m", "unittest", "discover", "-s", ".", "-p", "test_app.py"]
    environment:
      - FORCE_DYNAMIC_LIBEBM=true
    container_name: altrustworthyai_tests
